[package]
name = "OutlawSky"
version = "0.3.0"
authors = ["Paul Fidika (paul@fidika.com)"]
published-at = "0xeefcc463171fa02291bc96e8b398a1f8a0e81430e067ead2baf296adc80d2092"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }
SuiUtils = { local = "../../../packages/sui_utils" }
Ownership = { local = "../../../packages/ownership" }
TransferSystem = { local = "../../../packages/transfer_system" }
Attach = { local = "../../../packages/attach" }

[addresses]
outlaw_sky = "0xeefcc463171fa02291bc96e8b398a1f8a0e81430e067ead2baf296adc80d2092"
