[package]
name = "OutlawSky"
version = "0.1.0"
authors = ["Paul Fidika (paul@fidika.com)"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
SuiUtils = { local = "../../../packages/sui_utils" }
SuiMetadata = { local = "../../../packages/metadata" }
TransferSystem = { local = "../../../packages/transfer_system" }
Ownership = { local = "../../../packages/ownership" }

[addresses]
outlaw_sky = "0x3a2c283ae8f5693d19fc5607049cf75ad096c525"