[package]
name = "Capsule"
version = "0.1.0"
authors = ["Paul Fidika (paul@fidika.com)"]
published-at = "0xb8f4b2057dcf971ebd082343462e233c46562d7fbd808472ac978714f296f2e4"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }
SuiUtils = { local = "../sui_utils" }
Ownership = { local = "../ownership" }

[addresses]
# capsule =  "0x9ea11f1ad56df5d10450efafc35b142bae28677456701430712cd38ced31e60c" # Testnet
capsule =  "0xb8f4b2057dcf971ebd082343462e233c46562d7fbd808472ac978714f296f2e4"