[package]
name = "Attach"
version = "0.2.0"
authors = ["Paul Fidika (paul@fidika.com)"]
published-at = "0x0aa1b1745b1fcf5a48d5efcd90668d03bfe971604a4fde032b6c4178477836f4"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }
SuiUtils = { local = "../sui_utils" }
Ownership = { local = "../ownership" }

[addresses]
attach =  "0x0aa1b1745b1fcf5a48d5efcd90668d03bfe971604a4fde032b6c4178477836f4"