[package]
name = "SuiUtils"
version = "0.12.4"
published-at = "0x7317962252b09a4a38f06beadf8170fb50ea48b5a131e6a7598751ca61aea0e8" # Testnet

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }

[addresses]
sui_utils =  "0x7317962252b09a4a38f06beadf8170fb50ea48b5a131e6a7598751ca61aea0e8"
