[package]
name = "SuiUtils"
version = "0.12.4"
published-at = "0x6adaf7f9c1f7ae68b96dc85f5b069f4a6aabc748d8d741184ca5479fb4466bae"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }

[addresses]
sui_utils =  "0x6adaf7f9c1f7ae68b96dc85f5b069f4a6aabc748d8d741184ca5479fb4466bae" # testnet
# sui_utils =  "0x7317962252b09a4a38f06beadf8170fb50ea48b5a131e6a7598751ca61aea0e8" # localnet
