[package]
name = "Ownership"
version = "0.2.0"
authors = ["Paul Fidika (paul@fidika.com)"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
SuiUtils = { git = "https://github.com/0xcapsules/sui-utils.git", subdir = "package", rev = "master" }

[addresses]
ownership = "0xf62f0faaf30f2e073c42466e31748f9d96037e4c"