[package]
name = "Ownership"
version = "0.4.0"
authors = ["Paul Fidika (paul@fidika.com)"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }
SuiUtils = { local = "../sui_utils" }

[addresses]
ownership = "0x0"
